# Use the rest client extension from vs code to send these requests
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@url = {{mockLixiHost}}/as/token.oauth2

POST {{url}}
Content-Type:application/x-www-form-urlencoded

###

curl "{{url}}" -v -k