# @hostname = https://lixi-mock-valfirm-service.azurewebsites.net/pricefinder
@hostname = {{mockLixiHost}}/pricefinder

GET {{hostname}}/v1/images/900
Authorization:Bearer sometoken
Content-Type:application/json

###

POST {{hostname}}/v1/oauth2/token
Content-Type:application/x-www-form-urlencoded

client_id=bing
&client_secret=bong
&grant_type=bing

###

GET {{hostname}}/v1/properties/900/images
Authorization:Bearer sometoken
Content-Type:application/json

###

GET {{hostname}}/v1/suggest?q=4%20SOMERVILLE%20STREET,%20DONCASTER,%20VIC%203108&match_ids=false
Authorization:Bearer sometoken
Content-Type:application/json

###

GET {{hostname}}/v1/properties/900
Authorization:Bearer sometoken
Content-Type:application/json