# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and run tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev

    - name: Lint
      run: |
        chmod +x "${GITHUB_WORKSPACE}/scripts/lint.sh"
        ./scripts/lint.sh

    - name: Run test
      if: ${{ always() }}
      run: |
        chmod +x "${GITHUB_WORKSPACE}/scripts/test.sh"
        ./scripts/test.sh
